/**
 * Minimal CSV helpers shared by rewrite-queue related scripts. Values are trimmed and
 * quoted fields are unsupported: the data/ queue CSVs are generated by this repo.
 */

export function parseCsv(text, { skipComments = false, defaultHeaders = [] } = {}) {
  const lines = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !(skipComments && line.startsWith("#")));

  if (lines.length === 0) {
    return { headers: defaultHeaders, rows: [] };
  }

  const headers = lines[0].split(",").map((header) => header.trim());
  const rows = lines.slice(1).map((line) => {
    const values = line.split(",").map((value) => value.trim());
    return Object.fromEntries(
      headers.map((header, index) => [header, values[index] ?? ""]),
    );
  });

  return { headers, rows };
}

export function serializeCsv(headers, rows) {
  const body = rows.map((row) => headers.map((header) => row[header] ?? "").join(","));
  return `${[headers.join(","), ...body].join("\n")}\n`;
}
